---
always_allow_html: true
title: "D213 - Advanced Data Analytics"
author: "Sean P. Murphy"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
  always_allow_html: true
  html_notebook:
    toc: true
    toc_depth: 3
subtitle: Sentiment Analysis using Neural Networks
---

\newpage
# Introduction

## Assignment Background

## Initial Preparation


\newpage
***
# Part I:  Research Scope
***

## A1: Research Question

> Describe the purpose of this data analysis by doing the following:: Summarize one research question that you will answer using neural network models and NLP techniques. Be sure the research question is relevant to a real-world organizational situation and sentiment analysis captured in your chosen dataset.

## A2: Research Objective

> Describe the purpose of this data analysis by doing the following:: Define the objectives or goals of the data analysis. Be sure the objectives or goals are reasonable within the scope of the research question and are represented in the available data.

## A3: Research Mechanism

> Describe the purpose of this data analysis by doing the following:: Identify a type of neural network capable of performing a text classification task that can be trained to produce useful predictions on text sequences on the selected data set.


\newpage
***
# Part II:  Data Preparation
***


## B1: Exploratory Data Analysis

> Summarize the data cleaning process by doing the following: Perform exploratory data analysis on the chosen dataset, and include an explanation of each of the following elements:

•   presence of unusual characters (e.g., emojis, non-English characters, etc.)

•   vocabulary size

•   proposed word embedding length

•   statistical justification for the chosen maximum sequence length


## B2: Tokenization

> Summarize the data cleaning process by doing the following: Describe the goals of the tokenization process, including any code generated and packages that are used to normalize text during the tokenization process.

## B3: Padding

> Summarize the data cleaning process by doing the following: Explain the padding process used to standardize the length of sequences, including the following in your explanation:

•   if the padding occurs before or after the text sequence

•   a screenshot of a single padded sequence

## B4: Sentiment Categories

> Summarize the data cleaning process by doing the following:  Identify how many categories of sentiment will be used and an activation function for the final dense layer of the network.

## B5: Train/Test Split

> Summarize the data cleaning process by doing the following: Explain the steps used to prepare the data for analysis, including the size of the training, validation, and test set split.

## B6: Data Export

> Summarize the data cleaning process by doing the following: Provide a copy of the prepared dataset.



\newpage
***
# Part III:  Network Architecture
***

## C1: Model Summary

> Describe the type of network used by doing the following: Provide the output of the model summary of the function from TensorFlow.

## C2: Layers and Parameters

> Describe the type of network used by doing the following: Discuss the number of layers, the type of layers, and total number of parameters.

## C3: Hyperparameters

> Describe the type of network used by doing the following: Justify the choice of hyperparameters, including the following elements:

•   activation functions

•   number of nodes per layer

•   loss function

•   optimizer

•   stopping criteria

•   evaluation metric


\newpage
***
# Part IV:  Model Evaluation
***

## D1: Final Epoch

> Evaluate the model training process and its relevant outcomes by doing the following: Discuss the impact of using stopping criteria instead of defining the number of epochs, including a screenshot showing the final training epoch.

## D2: Loss Evaluation

> Evaluate the model training process and its relevant outcomes by doing the following: Provide visualizations of the model’s training process, including a line graph of the loss and chosen evaluation metric.

## D3: Model Fitness

> Evaluate the model training process and its relevant outcomes by doing the following: Assess the fitness of the model and any measures taken to address overfitting.

## D4: Predictive Accuracy

> Evaluate the model training process and its relevant outcomes by doing the following: Discuss the predictive accuracy of the trained network.


\newpage
***
# Part V:  Summary and Recommendations
***

## E: Code Copy

> Provide the code used to save the trained network within the neural network.

## F: Code Functionality

> Discuss the functionality of your neural network, including the impact of the network architecture.

## G: Recommendations

> Recommend a course of action based on your results.


\newpage
***
# Part VI: Reporting
***

## H: IDE Selection

  The entirety of this submission was authored within an R Notebook using RStudio Server version 2022.02.2, build number 485 (RStudio Team, 2022).  This instance was installed on a virtual instantiation of Ubuntu Server 20.04.4 LTS.
  
  As we have done with all other submissions in this program, we will include a knitted pdf of this executed notebook.


## I-J: Academic Integrity

  All sources for research and code usage have been cited in-text where appropriate, and a complete listing of these references is provided below.


## K:  Communication Standards
  
  Content has been edited for professionalism and appropriate communication standards.
  

\newpage

# References

RStudio Team (2022). RStudio: Integrated Development Environment for R. RStudio, PBC, Boston, MA. http://www.rstudio.com/.