---
always_allow_html: true
title: "D213 - Advanced Data Analytics"
author: "Sean P. Murphy"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_notebook: default
  always_allow_html: true
  pdf_document:
    toc: true
    toc_depth: 2
subtitle: Time Series Modeling
---



Part I:  Research Question

A.  Describe the purpose of this data analysis by doing the following:

1.  Summarize one research question that is relevant to a real-world organizational situation captured in the selected data set and that you will answer using time series modeling techniques.

2.  Define the objectives or goals of the data analysis. Ensure that your objectives or goals are reasonable within the scope of the scenario and are represented in the available data.

Part II:  Method Justification

B.  Summarize the assumptions of a time series model including stationarity and autocorrelated data.

Part III:  Data Preparation

C.  Summarize the data cleaning process by doing the following:

1.  Provide a line graph visualizing the realization of the time series.

2.  Describe the time step formatting of the realization, including any gaps in measurement and the length of the sequence.

3.  Evaluate the stationarity of the time series.

4.  Explain the steps used to prepare the data for analysis, including the training and test set split.

5.  Provide a copy of the cleaned dataset.

Part IV:  Model Identification and Analysis

D.  Analyze the time series dataset by doing the following:

1.  Report the annotated findings with visualizations of your data analysis, including the following elements:

•   the presence or lack of a seasonal component

•   trends

•   auto correlation function

•   spectral density

•   the decomposed time series

•   confirmation of the lack of trends in the residuals of the decomposed series

2.  Identify an autoregressive integrated moving average (ARIMA) model that takes into account the observed trend and seasonality of the time series data.

3.  Perform a forecast using the derived ARIMA model.

4.  Provide the output and calculations of the analysis you performed.

5.  Provide the code used to support the implementation of the time series model.

Part V:  Data Summary and Implications

E.  Summarize your findings and assumptions, including the following points:

1.  Discuss the results of your data analysis, including the following:

•   the selection of an ARIMA model

•   the prediction interval of the forecast

•   a justification of the forecast length

•   the model evaluation procedure and error metric

2.  Provide an annotated visualization of the forecast of the final model compared to the test set.

3.  Recommend a course of action based on your results.

Part VI:  Reporting

F.  Create your report from part E using an industry-relevant interactive development environment (e.g., a Jupyter Notebook). Include a PDF or HTML document of your executed notebook presentation.

G.  List the web sources used to acquire data or segments of third-party code to support the application.

H.  Acknowledge sources, using in-text citations and references, for content that is quoted, paraphrased, or summarized.

I.  Demonstrate professional communication in the content and presentation of your submission.


# References